version: '3'

volumes:
  postgres_data:
    driver: local

services:
  postgres:
    image: postgres:9.6
    volumes:
      # If the path does not exist, the volume is not created and the database
      # will be volatile (will exist only while the container exists)
      - postgres_data:/var/lib/postgresql/data3
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: passcloak
  keycloak:
    #image: faragom/sealoidc:latest
    image: sealoidc:latest
    environment:
      #PROXY_ADDRESS_FORWARDING: 'true'
      JAVA_OPTS: "-Xms64m -Xmx256m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true"
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: passcloak
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: adminpass
      KEYSTORE_PATH: /resources/testKeys/keystore.jks
      KEY_PASS: selfsignedpass
      STORE_PASS: keystorepass
      JWT_CERT_ALIAS: selfsigned
      HTTPSIG_CERT_ALIAS: 1
      SIGNING_SECRET: QjG+wP1CbAH2z4PWlWIDkxP4oRlgK2vos5/jXFfeBw8=
      ASYNC_SIGNATURE: 'true'
      EXPIRES: 5
      #TODO: cuando funcione, probar a comentar. Parece que no se utiliza
      CONFIG_JSON: /resources/configurationResponse.json
      #IDP_URL: http://dss.aegean.gr:8093
      #IDP_URL: https://dss.aegean.gr:8443
      #IDP_URI: /login
      IDP_URL: https://esmo-gateway.eu
      IDP_URI: /eid/login
      #ACM_URL: http://5.79.83.118:8070
      #ACM_URL: http://dss1.aegean.gr:8070
      ACM_URL: https://vm.project-seal.eu:9063
      ACM_URI: /rm/request
      SEAL_AUTH_REALM: auth
      #SESSION_MANAGER_URL: http://5.79.83.118:8090
      SESSION_MANAGER_URL: http://vm.project-seal.eu:9090
      CONFIGURATION_MANAGER_URL: https://vm.project-seal.eu:9083
      EIDAS_PROPERTIES: eduPersonUniqueId,eduPersonAffiliation,eduPersonPrimaryAffiliation,schacExpiryDate,mobile,eduPersonPrincipalName,PrioreduPersonPrincipalNamePrior,displayName,sn,eduOrgPostalAddress,eduOrgCn,schacHomeOrganization,edueduOrgLegalNameOrgCn,eduOrgL,edueduOrgLegalNameOrgCn
      ESMO_SUPPORTED_SIG_ALGORITHMS: RSA
      ESMO_SUPPORTED_ENC_ALGORITHMS: RSA
      DEFAULT_FINGERPRINT: 7a9ba747ab5ac50e640a07d90611ce612b7bde775457f2e57b804517a87c813b
      ESMO_SP_REQUEST_ISSUER: SPms001
      ESMO_SP_REQUEST_RECIPIENT: RMms001
      ESMO_SP_REQUEST_RECEIVER: RMms001
      ESMO_SP_REQUEST_SENDER: SPms001
      ESMO_SP_METADATA: https://aegean.gr/esmo/gw/sp/metadata
      ESMO_SP_NAME: SPms001
      ESMO_SP_LOCATION: Greece
      ESMO_SP_PROTOCOL: OIDC
      ESMO_EXPOSE_URL: /sp/response
      #https://domain:port/auth/realms/seal/sp/response
      ESMO_SP_OIDC_AUTH_ENDPOINT: http://esmo.uji.es:8180/auth/realms/seal/protocol/openid-connect/auth
      EIDAS_SP_OIDC_AUTH_ENDPOINT: http://esmo.uji.es:8180/auth/realms/eidas/protocol/openid-connect/auth
      ESMONO_SP_OIDC_AUTH_ENDPOINT: http://esmo.uji.es:8180/auth/realms/esmoNo/protocol/openid-connect/auth
      ESMONOPROD_SP_OIDC_AUTH_ENDPOINT: http://esmo.uji.es:8180/auth/realms/esmoNoProd/protocol/openid-connect/auth
      ESMO_NO_REALM: esmoNo
      ESMO_NO_PROD_REALM: esmoNoProd
    volumes:
      - ./resources:/resources
      - ./certs:/etc/x509/https
    ports:
      #- 8180:8080
      - 8180:8443
    depends_on:
      - postgres
